#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.6.0
# from Racc grammar file "".
#

require 'racc/parser.rb'
module Mydb
  module Parser
    class Parser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
     4,     5,    18,    19,     6,     7,     8,     9,    11,    13,
    17,    17,    17,    23,    24,    25 ]

racc_action_check = [
     0,     0,    14,    14,     1,     2,     5,     6,     8,    10,
    13,    16,    19,    21,    23,    24 ]

racc_action_pointer = [
    -3,     4,     3,   nil,   nil,     1,     7,   nil,    -1,   nil,
     3,   nil,   nil,     1,    -5,   nil,     2,   nil,   nil,     3,
   nil,     7,   nil,     5,     8,   nil ]

racc_action_default = [
   -13,   -13,   -13,    -2,    -3,   -13,   -13,    -1,   -13,    26,
   -13,   -12,    -4,   -13,   -13,    -6,   -13,   -11,    -5,   -13,
    -8,    -9,    -7,   -13,   -13,   -10 ]

racc_goto_table = [
    15,     1,     2,     3,    10,    12,    22,    14,    21,    20 ]

racc_goto_check = [
     7,     1,     2,     3,     4,     5,     7,     6,     8,     9 ]

racc_goto_pointer = [
   nil,     1,     2,     3,    -4,    -5,    -6,   -13,    -8,    -7 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    16,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 11, :_reduce_none,
  1, 12, :_reduce_none,
  1, 12, :_reduce_none,
  4, 13, :_reduce_4,
  3, 15, :_reduce_5,
  1, 16, :_reduce_6,
  3, 16, :_reduce_7,
  2, 17, :_reduce_none,
  1, 19, :_reduce_none,
  4, 19, :_reduce_none,
  1, 18, :_reduce_none,
  1, 14, :_reduce_none ]

racc_reduce_n = 13

racc_shift_n = 26

racc_token_table = {
  false => 0,
  :error => 1,
  :SEMICOLON => 2,
  :create_statement => 3,
  :CREATE => 4,
  :TABLE => 5,
  :LEFT_PAREN => 6,
  :RIGHT_PAREN => 7,
  :COMMA => 8,
  :IDENT => 9 }

racc_nt_base = 10

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "SEMICOLON",
  "create_statement",
  "CREATE",
  "TABLE",
  "LEFT_PAREN",
  "RIGHT_PAREN",
  "COMMA",
  "IDENT",
  "$start",
  "query",
  "statement",
  "r_CREATE_TABLE",
  "r_tbl_name",
  "r_create_definition_list",
  "r_comma_separated_create_definition",
  "r_create_definition",
  "r_col_name",
  "r_column_definition" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

module_eval(<<'.,.,', 'parser.y', 7)
  def _reduce_4(val, _values, result)
     result = Mydb::CreateCommand.new(val[2], val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 10)
  def _reduce_5(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 13)
  def _reduce_6(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 14)
  def _reduce_7(val, _values, result)
     result = val[0].append(val[2])
    result
  end
.,.,

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

def _reduce_none(val, _values, result)
  val[0]
end

    end   # class Parser
  end   # module Parser
end   # module Mydb

require_relative './parser.rex'

# INSERT customer (id, name) VALUE (10, 'aaa');
# SELECT * FROM customer;
